parameters: ~

services:
    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Reader\AnnotationReader:
        public: true

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Reader\AttributeReader:
        public: true

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\MetadataConfiguration:
        abstract: true
        arguments:
            - '@Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ClassesTypesMap'
            - '@overblog_graphql.metadata.reader'
            - '@Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\TypeGuesser\TypeGuesser'
            - '%overblog_graphql.schemas%'

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\EnumConfiguration:
        parent: Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\MetadataConfiguration
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Metadata\Enum',
              }

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\InputConfiguration:
        parent: Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\MetadataConfiguration
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Metadata\Input',
              }

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\InterfaceConfiguration:
        parent: Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\MetadataConfiguration
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Metadata\TypeInterface',
              }

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\ScalarConfiguration:
        parent: Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\MetadataConfiguration
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Metadata\Scalar',
              }

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\TypeConfiguration:
        parent: Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\MetadataConfiguration
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Metadata\Type',
              }
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Metadata\Provider',
              }

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\UnionConfiguration:
        parent: Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\MetadataConfiguration
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Metadata\Union',
              }

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\RelayEdgeConfiguration:
        parent: Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\MetadataConfiguration
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Metadata\Relay\Edge',
              }

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\RelayConnectionConfiguration:
        parent: Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\MetadataParser\MetadataConfiguration
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Metadata\Relay\Connection',
              }
