parameters: ~

services:
    overblog_graphql.arguments_transformer: '@Overblog\GraphQLBundle\Transformer\ArgumentsTransformer'

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ConfigurationMetadataParser:
        arguments:
            - '@overblog_graphql.metadata.reader'
            - '@Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ClassesTypesMap'
            - !tagged_iterator { tag: 'overblog_graphql.metadata.handler', index_by: 'annotationClass' }
            - '%graphql.configuration.directories.metadata%'
            - '%kernel.project_dir%'
            - '%kernel.bundles%'
        tags:
            - { name: 'overblog_graphql.configuration.provider' }

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ClassesTypesMap:
        public: true

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\Transformer\ArgumentsTransformer:
        arguments:
            - '@?validator'
            - '@Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ClassesTypesMap'

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ExpressionFunction\Arguments:
        tags: ['overblog_graphql.expression_function']
