parameters: ~

services:
    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ConfigurationMetadataParser:
        arguments:
            - '@Overblog\GraphQL\Bundle\Reader\AnnotationReader'
            - '@Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ClassesTypesMap'
            - !tagged_iterator { tag: 'overblog_graphql.metadata.handler', index_by: 'annotationClass' }
            - '%kernel.project_dir%'
            - '%kernel.bundles%'
        tags:
            - { name: 'overblog_graphql.configuration_generator' }

    Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ClassesTypesMap:
        public: true

    Overblog\GraphQL\Bundle\Reader\AnnotationReader:
        public: true

    Overblog\GraphQL\Bundle\TypeGuesser\TypeGuesser:
        arguments:
            - !tagged_iterator 'overblog_graphql.metadata.type_guesser_extension'

    Overblog\GraphQL\Bundle\TypeGuesser\Extension\TypeGuesserExtension:
        abstract: true
        arguments:
            - '@Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ClassesTypesMap'

    Overblog\GraphQL\Bundle\TypeGuesser\Extension\DocBlockTypeGuesserExtension:
        parent: Overblog\GraphQL\Bundle\TypeGuesser\TypeGuesserExtension
        targs:
            - { name: 'overblog_graphql.metadata.type_guesser_extension', priority: 100 }

    Overblog\GraphQL\Bundle\TypeGuesser\Extension\TypeHintTypeGuesserExtension:
        parent: Overblog\GraphQL\Bundle\TypeGuesser\TypeGuesserExtension
        targs:
            - { name: 'overblog_graphql.metadata.type_guesser_extension', priority: 50 }

    Overblog\GraphQL\Bundle\TypeGuesser\Extension\DoctrineTypeGuesserExtension:
        parent: Overblog\GraphQL\Bundle\TypeGuesser\TypeGuesserExtension
        targs:
            - { name: 'overblog_graphql.metadata.type_guesser_extension', priority: 0 }
        arguments:
            - '@Overblog\GraphQL\Bundle\ConfigurationMetadataBundle\ClassesTypesMap'
            - []
