parameters:

services:
    Overblog\GraphQL\Bundle\ConfigurationYamlBundle\ConfigurationYamlParser:
        arguments:
            - '%graphql.configuration.directories.yaml%'
            - '%kernel.project_dir%'
            - '%kernel.bundles%'
        tags:
            - { name: 'overblog_graphql.configuration.provider' }
