parameters:

services:
    Overblog\GraphQL\Bundle\ConfigurationYamlBundle\Generator\ConfigurationYamlParser:
        arguments:
            - ["%kernel.project_dir%/config/configuration/mapping"]
            - "%kernel.project_dir%"
            - "%kernel.bundles%"
        tags:
            - { name: "overblog_graphql.configuration_generator" }