parameters:

services:
    Overblog\GraphQL\Bundle\ConfigurationGraphQLBundle\ConfigurationGraphQLParser:
        arguments:
            - '%graphql.configuration.directories.graphql%'
            - '%kernel.project_dir%'
            - '%kernel.bundles%'
        tags:
            - { name: 'overblog_graphql.configuration.provider' }
